version: '3.1'

services:
  votting-app:
    build: vote
    ports:
      - 80:80
    depends_on:
      - redis
  redis:
    image: redis
  worker:
    build: worker
    depends_on:
      - redis
      - db
  db:
    image: postgres:9.4
    volumes:
      - data:/var/lib/postgresql/data
  result-app:
    build: result
    ports:
      - 5001:80
    environment:
      PORT: 80
    depends_on:
      - db

volumes:
  data: